### ISSUE TITLE
[Feature Request] multiple animations support?

### ISSUE THREAD

**Issue by ly525** [cycjimmy/swiper-animation#14]
I want to add the multiple animation to an element, now the swiper-animation only support only one animation when the swipper enter or leave the page

can you please support running multi animations?(first animation ends, the next animation runs)

**Comment by cycjimmy** [comment]
Thanks for your issue.

`swiper-animation` is originally designed to add some simple CSS animations for swiper elements when entering a slide and I did not consider the realization of complex animations. I will consider later whether it is suitable to add this feature. Currently, it seems that using js animation for running multi-animations is a more appropriate choice. You can try to use some js animation libraries such as `tween.js` to achieve your needs.

**Comment by ly525** [comment]
thanks for your advice, I will try the `tween.js` later.

**Comment by stephanebourquin** [comment]
Hi, thank for your script. It works great. But sometimes I use swiper in freemode, and I would like to trigger the animation just one time (the first one). ie. when it leaves the current active slide, the object desappears. And it is wrong for me. So is there a way to make this job with your script ? 
Thx a lot
