### ISSUE TITLE
trigger the animation just one time

### ISSUE THREAD

**Issue by stephanebourquin** [cycjimmy/swiper-animation#15]
Hi, thank for your script. It works great. But sometimes I use swiper in freemode, and I would like to trigger the animation just one time (the first one). ie. when it leaves the current active slide, the object disappears. And it is wrong for me. So is there a way to do this job with your script ?
Thx a lot

**Comment by cycjimmy** [comment]
Thanks for your issue. The element currently leaving an active slide will be cleaned up and returned to its initial state for the next execution of the animation. And the problem does occur. I will consider soon whether there is a reasonable solution to the issue.
