### ISSUE TITLE
New version Animate.css

### ISSUE THREAD

**Issue by azabroflovski** [cycjimmy/swiper-animation#17]
Hi, new Animate.css released. Сan u add support new version of [animate.css](https://animate.style/)
Thanks

**Comment by cycjimmy** [comment]
@azabroflovski 
Thanks for your issue. Animate.css@4 is supported now. 
See: https://github.com/cycjimmy/swiper-animation/blob/2baf71d30832ac694c30c30f844096f050fdebc6/README.md#add-attribute-on-elements-you-want-animated
