### ISSUE TITLE
Swiper Animation: Cannot read property 'isRecovery' of undefined

### ISSUE THREAD

**Issue by suyogn** [cycjimmy/swiper-animation#27]
**Describe the bug**
Cannot read property 'isRecovery' of undefined

**To Reproduce**
It will occurs runtime or change the orientation then reproduce this issue.

**Screenshots**
![swiper-animation](https://user-images.githubusercontent.com/43293138/118175427-b5c4ff00-b44d-11eb-9b73-3f770bbd467b.png)

**Comment by cycjimmy** [comment]
I cannot reproduce this bug. Can you provide a more detailed description? If applicable, provide an online demo to help explain your problem.
